[project]
name = "equipment-maintenance"
version = "6.0.0"
requires-python = ">=3.10"
dependencies = ["flet==0.86.5"]

[tool.flet]
org = "com.xitogen.suzhou"
product = "设备维护系统"
company = "Xitogen"
copyright = "2026"
build_number = 6

[tool.flet.android]
min_sdk_version = 23
target_sdk_version = 35
split_per_abi = false
